/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mineriadatos;

/**
 *
 * @author Sion
 */
public class DialogCluster extends javax.swing.JDialog {
    private final Ventana padre;

    /**
     * Creates new form DialogCluster
     */
    public DialogCluster(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        padre = (Ventana) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spinNumGrupos = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinNumIteraciones = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinSemilla = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAcepatr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones Cluster");
        setPreferredSize(new java.awt.Dimension(250, 170));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel1.setText("Numero de grupos");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 14));
        getContentPane().add(jLabel1);

        spinNumGrupos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(3), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinNumGrupos.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(spinNumGrupos);

        jLabel2.setText("Iteraciones máximas");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 14));
        getContentPane().add(jLabel2);

        spinNumIteraciones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(300), Integer.valueOf(1), null, Integer.valueOf(10)));
        spinNumIteraciones.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(spinNumIteraciones);

        jLabel4.setText("semilla");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 14));
        getContentPane().add(jLabel4);

        spinSemilla.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinSemilla.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(spinSemilla);

        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel3);

        jButton1.setText("Default");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        btnAcepatr.setText("Aceptar");
        btnAcepatr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepatrActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcepatr);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcepatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepatrActionPerformed
        int numGrupos = (int) spinNumGrupos.getValue();
        int numIter =  (int) spinNumIteraciones.getValue();
        int semilla =  (int) spinSemilla.getValue();
        padre.setOpcionesCluster(new OpcionesCluster(numGrupos, numIter, semilla));
        this.dispose();
    }//GEN-LAST:event_btnAcepatrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        spinNumGrupos.setValue(3);
        spinNumIteraciones.setValue(300);
        spinSemilla.setValue(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCluster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCluster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCluster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCluster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCluster dialog = new DialogCluster(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcepatr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinNumGrupos;
    private javax.swing.JSpinner spinNumIteraciones;
    private javax.swing.JSpinner spinSemilla;
    // End of variables declaration//GEN-END:variables
}
